### PR TITLE
Vulnerability: Use cvss_from and cvss_to params instead of cvss_filter

### PR DESCRIPTION
**Pull request by leSamo**
## Prerequisites

- ✔️ Scope your styles to your individual card
- ✔️ You are using translations when necessary with proper plural/singular modifications
- ✔️ You are using the template card provided
- ✔️ Use functional components & hooks (please)
- ✔️ Attach screenshots (before and after) - no UI change
- ✔️ Make sure that all text in blue is populated with the correct link. If you're unsure what the url should be, just ask!

## What
In vulnerability we are ditching cvss_filter URL param which has only 3 options in favour of cvss_from and cvss_to for more customizability.

[Corresponding vuln PR](https://github.com/RedHatInsights/vulnerability-ui/pull/655)

## Screenshots
No UI change

## Code Review
@christiemolloy @ryelo @AllenBW

### CODE REVIEW

**Comment by AllenBW** [comment]
@leSamo this api on prod-stable? orrrr not quite

**Review by AllenBW — CHANGES_REQUESTED** [review]
Looks like this work is a regression, in the sense that we lose filter chips when clicking the links, (maybe that other pr has to be merged?) 

in the future, keep things as a draft pr until they're g2g

**Comment by leSamo** [comment]
@AllenBW this API is currently not in prod-stable, only ci-beta, because if we push it before this PR, page would crash when user would navigate from dashboard to vuln with CVSS filter. If this PR was in prod, and ours change wasn't, only the chips would be missing. We will try to push our changes to prod as soon as this PR is out. Makes sense?

**Review by AllenBW — APPROVED** [review]
@leSamo okie dokie, i'll merge it around 7est, if yah so it should be up when yer waking up if yah wanta then push the api, looking to minimize weird time for users 👍

**Comment by AllenBW** [comment]
@leSamo merged n pushed! should be in prod in ah few shakes

**Comment by leSamo** [comment]
@AllenBW Thank you!

**Pull request merged**
