### PR TITLE
Update packages for working snapshot tests

### PR DESCRIPTION
**Pull request by AsToNlele**
Had to update packages like in other apps. Also added packages which will be needed for testing.

### CODE REVIEW

**Comment by AsToNlele** [comment]
after this is merged I will push a test for AdvisorCard

**Review by gabipodolnikova — CHANGES_REQUESTED** [review]
I found just one small styling issue on the Drift card - under `Investigate in Drift` button there is no longer a padding.

Also could you please fix the console errors? It should be enough to remove having `key` as an index. Just search where `DataListCell` is used and replace it with something that has more description to it :D 

Otherwise it looks great, it will also help to fix a styling issue in Inventory with this Frontend components update, so thank you!

**Comment by AsToNlele** [comment]
Thanks for your review! I've fixed the console errors, but I don't see the styling issue on the Drift card 😿

image

**Review by gabipodolnikova — APPROVED** [review]
I don't see the styling issue now either, weird :D So great, LGTM! :)

**Pull request merged**
