### PR TITLE
vulnerabilities to vulnerability

### PR DESCRIPTION
**Pull request by ryelo**
## What

Updated Vulnerabilities to Vulnerability in a couple places

### CODE REVIEW

**Comment by AllenBW** [comment]
🏴‍☠️ 🦨  conflict ahoy

**Comment by AllenBW** [comment]
ok this is annoying... maybe we ignore the the messages.json till we actually need it for translations (if ever?) n just build it at that point in time

thoughts @ryelo 🤔

**Comment by ryelo** [comment]
They get generated on build, so maybe we don't need to upload them to github?

**Comment by AllenBW** [comment]
wanta add an ignore to this pr n we'll make everyone happy?

**Comment by ryelo** [comment]
I'm gonna throw it on another PR real quick

**Pull request merged**
