### PR TITLE
[Prod-beta] 2020 April 6 push

### PR DESCRIPTION
**Pull request by ryelo**
Just taking what's on ci-beta and mashing it to prod-beta!

On hold until https://github.com/RedHatInsights/cloud-services-config/pull/159

### CODE REVIEW

**Comment by ryelo** [comment]
No squashing here. Going to rebase it

**Comment by AllenBW** [comment]
Rebase might conflict... looks like it does :grim

**Comment by ryelo** [comment]
i'll force it! closing this!

**Comment by ryelo** [comment]
oh github is smarter than I thought it would be

**Pull request merged**
