### PR TITLE
VULN-1471 Enable global filter for Vulnerability card

### PR DESCRIPTION
**Pull request by katerinapat**
## What

Enable global filtering for the vulnerability card. The PR introduce

1. introduce a new vuln API that supports global filtering 
2. remove `FilterNotSupported` from the card
3. remove package `urijs` which was used only by vuln app 

### Before
NO ui changes

### After
vuln-global-filter

## Code Review
@christiemolloy @ryelo @AllenBW

## Design Review
@kybaker

### CODE REVIEW

**Comment by AllenBW** [comment]
@katerinapat Is the api for this on prod-stable?

**Comment by katerinapat** [comment]
@AllenBW No, only in CI.

**Comment by katerinapat** [comment]
@AllenBW The API landed in prod stable

**Review by AllenBW — APPROVED** [review]
Added the missing lockfile, N WE'RE GOOD TO GO 🚀 🤘 🌮

**Comment by AllenBW** [comment]
Sent away to prod-beta! When everything checks out there, we'll shuffle along to stable

**Pull request merged**
